### ISSUE TITLE
Update User Profile

### ISSUE THREAD

**Issue by kipchubett** [corneliouzbett/MedicationManager#3]
user should be able to update their profile once login.

**Comment by illisha** [comment]
Even after registering I am unable to log in. Could you tell me how to go about it?

**Comment by kipchubett** [comment]
> Even after registering I am unable to log in. Could you tell me how to go about it?

Are you able to register successful

**Comment by illisha** [comment]
Yes. The registration is successful but the same credentials do not work if
I try to log in right after that.

**Comment by kipchubett** [comment]
For me it's working fine. I can't reproduce your error . Just run it in
debug mode andorid studio. Then you can send me the error message

**Comment by illisha** [comment]
Okay I'll do that. Also can you give me trial values for register here page
and then the main login and password page. I'll input the exact same values
and check if it works.

**Comment by kipchubett** [comment]
Unfortunately it's my personal email credentials. So i can share but Am
creating a test account will definitely share with you

**Comment by illisha** [comment]
Yeah yeah even a test account is fine. Just lemme know any input that'll
give me an access to what lies ahead!
